const ADD_NEIGHBOR = 'ADD_NEIGHBOR';
const CHANGE_FOCUS_ELEMENT = 'CHANGE_FOCUS_ELEMENT';
const UPDATE_NOTE_BODY = 'UPPDATE_NOTE_BODY';
const USER_LOGGED_IN = 'USER_LOGGED_IN';
const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
const GET_USER_DATA = 'GET_USER_DATA';
const ADD_SHORTCUT = 'ADD_SHORTCUT';

const ADD_NOTE = 'ADD_NOTE';

const UPDATE_CONTENT = 'UPDATE_CONTENT';
const UPDATE_CONTENT_REQUESTED = 'UPDATE_CONTENT_REQUESTED';
const UPDATE_CONTENT_RECEIVED = 'UPDATE_CONTENT_RECEIVED';
const UPDATE_CONTENT_FAILED = 'UPDATE_CONTENT_FAILED';

export {
  ADD_NEIGHBOR,
  CHANGE_FOCUS_ELEMENT,
  ADD_NOTE,
  UPDATE_NOTE_BODY,
  USER_LOGGED_IN,
  USER_LOGGED_OUT,
  UPDATE_CONTENT_REQUESTED,
  UPDATE_CONTENT_RECEIVED,
  UPDATE_CONTENT_FAILED,
  UPDATE_CONTENT,
  GET_USER_DATA,
  ADD_SHORTCUT,
};
