const ADD_NEIGHBOR = 'ADD_NEIGHBOR';
const CHANGE_FOCUS_ELEMENT = 'CHANGE_FOCUS_ELEMENT';
const UPDATE_NOTE_BODY = 'UPPDATE_NOTE_BODY';
const USER_LOGGED_IN = 'USER_LOGGED_IN';
const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

const ADD_NOTE = 'ADD_NOTE';

export {
  ADD_NEIGHBOR, CHANGE_FOCUS_ELEMENT,
  ADD_NOTE, UPDATE_NOTE_BODY, USER_LOGGED_IN, USER_LOGGED_OUT,
};
